apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "catboost-iris"
spec:
  predictor:
    catboost:
      storageUri: "https://raw.githubusercontent.com/chethanuk/kserve/72f5b9f413b987bdcfa76c7fdaa467bb01b8f80e/python/catboostserver/example_model/model/model.cbm"
